#ifndef GE_TYPEWRITER_H
#define GE_TYPEWRITER_H

enum TYPEWRITER_SCENES
{
    TYPEWRITER_INTRO,
    TYPEWRITER_CREDITS,
    TYPEWRITER_INTRO2,
    TYPEWRITER_INTRO3,
    TYPEWRITER_TITLE,
    TYPEWRITER_GARBAGE,
    TYPEWRITER_MSG,
    TYPEWRITER_NEW_BERLIN,
    TYPEWRITER_DOG_AND_PONY,
    TYPEWRITER_GAME_OVER,
    TYPEWRITER_BUFFER
};

enum TYPEWRITER_TYPE
{
    TYPE_TEXT,
    TYPE_IMG
};

void typewriter(int scene);

#endif