// main_auto.h

#ifndef MAIN_AUTO_H
#define MAIN_AUTO_H

enum progress
{
	CUTSCENE_TO_GARBAGE,
	FOREST_01,
	PIT_01,
	NEW_BERLIN,
	DOG_AND_PONY,
	WAKEY_WAKEY,
	DARK_TO_DARK,
	CUTSCENE_CHANNEL,
	BLACK_TO_BEACH,
	FLAYITHRO_AWAKE,
	BLACK_TO_TRAIN,
	BLACK_TO_CANTERBURY,
	BLACK_TO_LAB_02,
	CH_CUTSCENE_07,
	CH_CUTSCENE_08,
	CH_CUTSCENE_08B,
	CH_CUTSCENE_08C,
	CUTSCENE_01,
	CH_SANS,
	CH_TITLE,
	CH_CUTSCENE_05,
	CH_CUTSCENE_09,
	CH_CUTSCENE_03,
	CH_CUTSCENE_01,
	CH_CUTSCENE_02,
	BLACK_TO_DEATH,
	CH_CUTSCENE_04,
	CH_CUTSCENE_06,
};

void resolve_chapter();

#endif